[package]
name = "microservice"
version = "0.1.0"
authors = ["Michał Pokrywka", "Vlad Ovinnikov"]
edition = "2018"

[features]
default = ["pgsql"]
pgsql = ["diesel", "r2d2", "r2d2-diesel"]
swagger = ["paperclip"]

[dependencies]
actix-cors = "0.2"
actix-http = "1.0"
actix-rt = "1.0"
actix-service = "1.0"
actix-web = "2.0"
bytes = "0.5"
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "1.4", features = ["postgres", "chrono"], optional = true }
dotenv = "0.15"
futures = "0.3"
jsonwebtoken = "7"
log = "0.4"
microservice_derive = { path = "microservice_derive" }
num_cpus = "1"
paperclip = { git = "https://github.com/wafflespeanut/paperclip", features = ["actix", "rust_decimal"], optional = true }
r2d2-diesel = { version = "1.0", optional = true }
r2d2 = { version = "0.8", optional = true }
serde = "1.0"
serde_derive = "1.0"
validator = "0.10"
colored = "1.9"

[patch.'https://github.com/wafflespeanut/paperclip']
# paperclip = { git = "https://github.com/sfisol/paperclip", branch = "feature/actix-multipart" }
# paperclip = { path = "../paperclip" }

